#!/bin/bash

# Helper Functions
function new_separator() {
  printf "%0.s-" {1..50}
  printf "\n"
}

function new_small_separator() {
	printf "%0.s-" {1..25}
	printf "\n"
}

function echo_header() {
    tput setaf 1; echo -e "\033[46m $1 \033[0m"; tput sgr0
}

function echo_message() {
   tput setaf 2; echo $1; tput sgr0
}

function echo_error() {
  tput setaf 1; echo $1; tput sgr0
}

# checks if the Ubuntu Desktop libaries are installed
function is_ubuntu_desktop() {
  dpkg -l ubuntu-desktop >/dev/null 2>&1 || return 1
}


export -f new_small_separator
export -f echo_message
export -f echo_error
export -f is_ubuntu_desktop


declare -A ALL_OPTIONS 
ALL_OPTIONS["system"]="Basic System Installation"
ALL_OPTIONS["dotfiles"]="Link dotfiles to home directory"
ALL_OPTIONS["docker"]="Install Docker"
ALL_OPTIONS["docker-compose"]="Install Docker-Compose"
ALL_OPTIONS["go"]="Install Go"
ALL_OPTIONS["favorite-apps"]="Update your Favorite Apps (only Desktop Version)"
ALL_OPTIONS["ide"]="Install some Jetbrains IDE (only Desktop Version)"
ALL_OPTIONS["vscode"]="Install VSCode with some extensions (only Desktop Version)"

show_help() {
   echo "Usage: $(basename $0)  [options]"
   echo ""
   echo "Options:"
   for option in "${!ALL_OPTIONS[@]}"; do
    printf "%5s %-20s %s \n" "" $option	"${ALL_OPTIONS[$option]}"
   done

}

install_option() {
  option=$1
  new_separator
  echo_header "Starting to install ${option}"
  chmod +x "./install/$option-install.sh"
  if [ $? = 127 ];
  then
    echo_error "'$option' is an unknown command"
    echo ""
    show_help
    exit 1
  fi
  "./install/$option-install.sh"
  echo_message "Finished to install ${option}"
}

install_all() {
  echo_message "Installing All Options"
  for option in "${!ALL_OPTIONS[@]}"; do
    install_option $option
  done
}


case "$1" in 
  "" | "-h" | "--help")   show_help  ;;
  "all")                  install_all ;;
  *)
    for option in "$@"
    do
      install_option $option
    done
    ;;
esac
